name: Nightly build

on:
  schedule:
    - cron: '0 10 * * *' # run at 10 AM UTC

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Fetch tool
        run: ./fetch-tool.sh

      - name: Build rootfs
        run: ./make-rootfs.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          release_name: Release nightly
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rootfs.tar.gz
          asset_name: rootfs.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset (Hash)
        id: upload_release_asset_hash
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rootfs.tar.gz.sha256
          asset_name: rootfs.tar.gz.sha256
          asset_content_type: text/plain
